football/urls.py
from django.conf.urls.defaults import patterns, url, include

from football.models import League, Team


urlpatterns = patterns('',

    url(
        r'^league-logs/$',
        'football.views.league_logs',
        name='league-logs'
    ),
    
    url(
        r'^league-fixtures/$',
        'football.views.league_fixtures',
        name='league-fixtures'
    ),

     url(
        r'^league-results/$',
        'football.views.league_results',
        name='league-results'
    ),

    url(
        r'^league-dashboard/(?P<slug>[\w-]+)/$', 
        'football.views.league_dashboard', 
        {}, 
        name='league_object_detail'
    ),

    url(
        r'^top-leagues-menu-ajax/$',
        'django.views.generic.simple.direct_to_template',
        {
            'template':'football/top_leagues_menu_ajax.html', 
        },
        name='top-leagues-menu-ajax'
    ),

    url(
        r'^more-leagues-menu-ajax/$',
        'django.views.generic.simple.direct_to_template',
        {
            'template':'football/more_leagues_menu_ajax.html', 
        },
        name='more-leagues-menu-ajax'
    ),

    url(
        r'^top-teams-menu-ajax/$',
        'django.views.generic.simple.direct_to_template',
        {
            'template':'football/top_teams_menu_ajax.html', 
        },
        name='top-teams-menu-ajax'
    ),

    url(
        r'^league-logs-widget/(?P<league_slug>[\w-]+)/$', 
        'football.views.league_logs_widget', 
        {}, 
        name='league-logs-widget'
    ),

    url(
        r'^league-fixtures-widget/(?P<league_slug>[\w-]+)/$', 
        'football.views.league_fixtures_widget', 
        {}, 
        name='league-fixtures-widget'
    ),

    url(
        r'^league-results-widget/(?P<league_slug>[\w-]+)/$', 
        'football.views.league_results_widget', 
        {}, 
        name='league-results-widget'
    ),

    url(
        r'^league-posts/(?P<slug>[\w-]+)/$', 
        'jmbo.generic.views.generic_object_detail',
        {'queryset':League.permitted.all(), 'template_name':'football/league_posts.html'},
        name='league-posts'
    ),

    url(
        r'^league-galleries/(?P<slug>[\w-]+)/$', 
        'jmbo.generic.views.generic_object_detail',
        {'queryset':League.permitted.all(), 'template_name':'football/league_galleries.html'},
        name='league-galleries'
    ),

    url(
        r'^team-fixtures-widget/(?P<team_slug>[\w-]+)/$', 
        'football.views.team_fixtures_widget', 
        {}, 
        name='team-fixtures-widget'
    ),

    url(
        r'^team-results-widget/(?P<team_slug>[\w-]+)/$', 
        'football.views.team_results_widget', 
        {}, 
        name='team-results-widget'
    ),
    
    url(
        r'^team-players-widget/(?P<team_slug>[\w-]+)/$', 
        'football.views.team_players_widget', 
        {}, 
        name='team-players-widget'
    ),

    url(
        r'^team-players/(?P<slug>[\w-]+)/$', 
        'jmbo.generic.views.generic_object_detail',
        {'queryset':Team.permitted.all(), 'template_name':'football/team_players.html'},
        name='team-players'
    ),

    url(
        r'^team-dashboard/(?P<slug>[\w-]+)/$', 
        'football.views.team_dashboard', 
        {}, 
        name='team_object_detail'
    ),

    url(
        r'^live-scores/$', 
        'football.views.live_scores', 
        {}, 
        name='live-scores'
    ),

    url(
        r'^football-live-commentary/$', 
        'football.views.live_commentary', 
        {}, 
        name='live-commentary'
    )

)   

football/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from ckeditor.fields import RichTextField
from jmbo.models import ModelBase
from jmbo.utils import generate_slug


class LeagueGroup(models.Model):
    title = models.CharField(max_length=64)
    subtitle = models.CharField(
        max_length=255, 
        null=True, 
        blank=True, 
        help_text='Some titles may be the same. A subtitle makes a distinction. It is not displayed on the site.',
    )
    position = models.PositiveIntegerField(default=0, db_index=True)
    football365_di = models.PositiveIntegerField(
        null=True, blank=True, db_index=True
    )
    football365_ci = models.PositiveIntegerField(
        null=True, blank=True, db_index=True
    )

    def __unicode__(self):
        if self.subtitle:
            return '%s (%s)' % (self.title, self.subtitle)
        else:
            return self.title


class League(ModelBase):
    region = models.CharField(
        max_length=32,
        choices=(
            ('local', 'Local'),
            ('regional', 'Regional'),
            ('international', 'International'),
        ),
    )
    position = models.PositiveIntegerField(default=0, db_index=True)    
    football365_di = models.PositiveIntegerField(
        null=True, blank=True, db_index=True
    )
    football365_ci = models.PositiveIntegerField(
        null=True, blank=True, db_index=True
    )
    groups = models.ManyToManyField(LeagueGroup, null=True, blank=True)

    @property
    def logentries(self):
        return self.logentry_set.all().order_by('group', 'group__position', '-points', '-goal_difference')


class Team(ModelBase):
    abbreviated_title = models.CharField(
        max_length=10,
        null=True,
        blank=True
    )
    leagues = models.ManyToManyField(League)
    info = RichTextField(null=True, blank=True)
    history = RichTextField(null=True, blank=True)
    statistics = RichTextField(null=True, blank=True)
    football365_teamcode = models.CharField(
        max_length=64, null=True, blank=True, db_index=True
    )

    class Meta:
        ordering = ('title',)

    @property
    def players(self):
        return Player.permitted.filter(teams=self).order_by('title')


class Fixture(models.Model):
    league = models.ForeignKey(League)
    group = models.ForeignKey(LeagueGroup, null=True, blank=True)
    datetime = models.DateTimeField()
    home_team = models.ForeignKey(Team, related_name='home_team')
    away_team = models.ForeignKey(Team, related_name='away_team')
    home_score = models.PositiveIntegerField(null=True, blank=True)
    away_score = models.PositiveIntegerField(null=True, blank=True)
    completed = models.BooleanField(default=False)

    def __unicode__(self):
        return '%s vs. %s %s' % \
            (
                self.home_team.title, 
                self.away_team.title, 
                self.datetime.strftime('%d %B %Y')
            )


class LogEntry(models.Model):
    league = models.ForeignKey(League)
    group = models.ForeignKey(LeagueGroup, null=True, blank=True)
    team = models.ForeignKey(Team)
    played = models.PositiveIntegerField(default=0)
    won = models.PositiveIntegerField(default=0)
    drawn = models.PositiveIntegerField(default=0)
    lost = models.PositiveIntegerField(default=0)
    goals = models.PositiveIntegerField(default=0)
    points = models.PositiveIntegerField(default=0)
    goal_difference = models.IntegerField(default=0)

    class Meta:
        unique_together = (('league', 'team'),)
        verbose_name_plural = 'Log Entries'

class Trivia(ModelBase):
    pass

class Player(ModelBase):
    teams = models.ManyToManyField(Team)

football/templates/basic/football/inclusion_tags/league_detail.html
{% load i18n jmbo_inclusion_tags %}

<div class="object-detail-inclusion league-detail-inclusion">
    {% if not 'img' in object.content %}
        <img src="{{ object.get_league_detail_url }}" width="269" height="151" alt="" />
    {% endif %}

    {% if object.team_set.all.exists %}
    <div class="teams">
        <label>{% trans "Teams" %}</label>
        {% for object in object.player_set.all %}
            <div class="item {% if forloop.first %}first{% endif %} {% if forloop.last %}last{% endif %}">
                {% render_object object.as_leaf_class "list_item_ipod" %}
            </div>
        {% endfor %}
    </div>
    {% endif %}
</div>

football/templates/basic/football/inclusion_tags/live_scores.html
{% load i18n %}

{% if live_scores %}
    <div class="live-scores-inclusion">
	    {% trans "Live scores" %}:{% for score in live_scores %} <a href="{% url live-scores %}">{{ score.HOMETEAM }} {{ score.HOMETEAMSCORE }} : {{ score.AWAYTEAM }} {{ score.AWAYTEAMSCORE }}</a>{% endfor %}
	</div>
{% endif %}

football/templates/basic/football/inclusion_tags/player_detail.html
{% load jmbo_inclusion_tags %}

<div class="object-detail-inclusion team-detail-inclusion">
    <img src="{{ object.get_player_detail_LAYER_url }}" alt="" />
</div>

football/templates/basic/football/inclusion_tags/player_list_item_ipod.html
{% load jmbo_template_tags foundry_tags %}

<a href="{{ object.get_absolute_url }}">
    <img src="{{ object.get_listing_horizontal_player_LAYER_url }}" alt="{{ object.title }}" />
</a>

<div class="title">
    {% if object.categories.all.count %}<span class="category">{{ object.categories.all|join_titles }}:</span>{% endif %}
    <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
</div>

{% include "includes/list_meta.html" %}

football/templates/basic/football/inclusion_tags/team_detail.html
{% load i18n jmbo_inclusion_tags jmbo_template_tags foundry_tags %}

<div class="object-detail-inclusion team-detail-inclusion">
    {% if not 'img' in object.info %}
        <img src="{{ object.image_detail_url }}" alt="" />
    {% endif %}

    {% if object.info %}
        {{ object.info|safe }}
    {% endif %}

    <div class="clear"></div> 

    {% if object.history %}
        <div class="history">
            <label>{% trans "History" %}</label>
            {{ object.history|safe }}
        </div>
    {% endif %}

    {% if object.statistics %}
        <div class="statistics">
            <label>{%trans "Statistics" %}</label>
            {{ object.statistics|safe }}
        </div>
    {% endif %}

    {% comment %}
    {% if object.player_set.all.exists %}
    <div class="players">
        <label>{%trans "Players" %}</label>
        <div class="foundry-container foundry-listing-horizontal">
        <div class="items">
        {% for object in object.player_set.all %}
            <div class="item {% if forloop.first %}first{% endif %} {% if forloop.last %}last{% endif %} item-{{ object.class_name|lower }}">
                {% render_object object "list_item_ipod" %}
            </div>
        {% endfor %}
        </div>
        </div>
    </div>
    {% endif %}

    {% get_relation_list 'team_galleries' for object as 'team_galleries' %}
    {% if team_galleries %}
    <div class="galleries">
        <label>{%trans "Galleries" %}</label>
        {% for object in team_galleries %}
            <div class="item {% if forloop.first %}first{% endif %} {% if forloop.last %}last{% endif %}">
                {% render_object object "list_item_ipod" %}
            </div>
        {% endfor %}
    </div>
    {% endif %}
    {% endcomment %}

</div>

football/templates/basic/football/inclusion_tags/trivia_list_item.html
{{ object.description }}